### ISSUE TITLE
Failed to execute cbi dispatcher target for entry '/admin/services/AdGuardHome

### ISSUE THREAD

**Issue by boshi116** [happyzhang1995/openwrt-adguardhome#1]
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/services/AdGuardHome'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/AdGuardHome.lua:20: attempt to concatenate global 'port' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

**Comment by happyzhang1995** [comment]
已修复
